PREFIX ns: <https://example.org/partidos/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Consulta federada: Enriquecer deportes con imagen y descripción de Wikidata
SELECT ?nombreDeporte ?descripcion ?imagen
WHERE {
  ?deporte a ns:Deporte .
  ?deporte ns:nombreDeporte ?nombreDeporte .
  ?deporte ns:sameAsDeporte ?wdDeporte .
  
  SERVICE <https://query.wikidata.org/sparql> {
    OPTIONAL { 
      ?wdDeporte rdfs:label ?descripcion .
      FILTER(LANG(?descripcion) = "es")
    }
    OPTIONAL { ?wdDeporte wdt:P18 ?imagen . }
  }
}
