
abstract=
ontologyTitle=Ontología de las Playas con bandera azul 2025 de Galicia
ontologyPrefix=[Ontology NS Prefix]
ontologyNamespaceURI=http://example.org/def/gamere#
ontologyName=Ontología de las Playas con bandera azul 2025 de Galicia
thisVersionURI=null
latestVersionURI=
previousVersionURI=
dateCreated=
dateModified=
ontologyRevisionNumber=1.0
licenseURI=null
licenseName=null
licenseIconURL=null
citeAs= Ontología de las Playas con bandera azul 2025 de Galicia. Revision: 1.0.
DOI=
status=Ontology Specification Draft
logo=
description=Ontología diseñada para describir las playas con bandera azul 2025 de Galicia, incluyendo su ubicación, concellos y provincias
introduction=
backwardsCompatibleWith=
publisher=
publisherURI=
publisherInstitution=
publisherInstitutionURI=
authors=
authorsURI=
authorsInstitution=
authorsInstitutionURI=
contributors=
contributorsURI=
contributorsInstitution=
contributorsInstitutionURI=
importedOntologyNames=
importedOntologyURIs=
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=
source=
seeAlso=
fundingGrants=
funders=
