PREFIX ta: <http://example.org/def/juegosdeportivosmunicipalesmadrid#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>

SELECT ?nombreCampo ?wikidata ?wikidataLabel ?coords ?streetAddress
WHERE {
  ?campo a ta:Campo ;
         ta:nombreCampo ?nombreCampo ;
         owl:sameAs ?wikidata .

  SERVICE <https://query.wikidata.org/sparql> {
    OPTIONAL { ?wikidata wdt:P625 ?coords . }
    OPTIONAL { ?wikidata wdt:P6375 ?streetAddress . }
    SERVICE wikibase:label {
      bd:serviceParam wikibase:language "es,en" .
      ?wikidata rdfs:label ?wikidataLabel .
    }
  }
}
ORDER BY ?nombreCampo
