PREFIX ta: <http://example.org/def/juegosdeportivosmunicipalesmadrid#>

SELECT ?nombreDistrito (COUNT(DISTINCT ?partido) AS ?totalPartidos)
WHERE {
  ?partido a ta:Partido ;
           ta:seJuegaEn ?campo .
  ?campo ta:estaEn ?distrito .
  ?distrito ta:nombreDistrito ?nombreDistrito .
}
GROUP BY ?nombreDistrito
ORDER BY DESC(?totalPartidos)
